services:
  - type: web
    name: melonku-be
    env: php
    plan: free
    buildCommand: composer install --no-dev --optimize-autoloader
    startCommand: heroku-php-apache2 public/
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: DOCUMENT_ROOT
        value: public
      - key: APP_KEY
        value: base64:7K5060r5V6i9ZzO5bL9J4T2c6O7N0u8M=
      - key: DB_CONNECTION
        value: mysql
      - key: DB_PORT
        value: "3306"
      - key: DB_HOST
        sync: false
      - key: DB_DATABASE
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: RAJAONGKIR_API_KEY
        sync: false
      - key: MIDTRANS_SERVER_KEY
        sync: false
      - key: MIDTRANS_CLIENT_KEY
        sync: false
